version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sports_rental_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sports_rental_db
      POSTGRES_USER: sports_user
      POSTGRES_PASSWORD: Sports2024!
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sports_user -d sports_rental_db"]
      interval: 2s
      timeout: 3s
      retries: 10

  web:
    build: .
    container_name: sports_rental_web
    command: sh -c "sleep 5 && python manage.py migrate && python manage.py create_superuser && python manage.py seed_data && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      DB_NAME: sports_rental_db
      DB_USER: sports_user
      DB_PASSWORD: Sports2024!
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SUPERUSER_USERNAME: adminsite
      DJANGO_SUPERUSER_EMAIL: fdavisarz10@gmail.com
      DJANGO_SUPERUSER_PASSWORD: xz123xz
      DJANGO_SUPERUSER_FIRSTNAME: Technical
      DJANGO_SUPERUSER_LASTNAME: Admin
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: